import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#121212',
    },
    topSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingTop: 60,
        paddingBottom: 20,
    },
    groupSection: {
        position: 'relative',
        zIndex: 10,
    },
    groupDropdown: {
        backgroundColor: '#FF6B35',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        gap: 8,
    },
    groupDropdownText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
    },
    dropdownArrow: {
        color: '#FFFFFF',
        fontSize: 12,
    },
    dropdownMenu: {
        position: 'absolute',
        top: 40,
        left: 0,
        backgroundColor: '#333333',
        borderRadius: 12,
        minWidth: 120,
        zIndex: 20,
        overflow: 'hidden',
    },
    dropdownItem: {
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    dropdownItemText: {
        color: '#FFFFFF',
        fontSize: 14,
    },
    addGroupButton: {
        backgroundColor: 'transparent',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#FF6B35',
    },
    addGroupText: {
        color: '#FF6B35',
        fontSize: 14,
    },
    sortSection: {
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    sortButtonContainer: {
        flexDirection: 'row',
        backgroundColor: '#3F3F42',
        borderRadius: 25,
        padding: 2,
    },
    sortButton: {
        flex: 1,
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 23,
        alignItems: 'center',
    },
    activeSortButton: {
        backgroundColor: '#6B6B6B',
    },
    inactiveSortButton: {
        backgroundColor: 'transparent',
    },
    sortButtonText: {
        fontSize: 14,
    },
    activeSortText: {
        color: '#FFFFFF',
    },
    inactiveSortText: {
        color: '#9E9E9E',
    },
    up: {
        backgroundColor: '#2E2E2E',
        marginHorizontal: 20,
        borderRadius: 20,
        paddingTop: 30,
        paddingBottom: 20,
        marginBottom: 20,
        shadowColor: '#FF6B35',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 8,
    },
    podiumContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'flex-end',
        paddingHorizontal: 20,
        height: 200,
    },
    firstPlace: {
        alignItems: 'center',
        marginHorizontal: 10,
    },
    secondPlace: {
        alignItems: 'center',
        marginHorizontal: 10,
    },
    thirdPlace: {
        alignItems: 'center',
        marginHorizontal: 10,
    },
    iconPlaceholder: {
        width: 30,
        height: 30,
        backgroundColor: 'transparent',
        marginBottom: 10,
    },
    firstPodium: {
        backgroundColor: '#FF6B35',
        width: 80,
        height: 100,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
        elevation: 8,
    },
    secondPodium: {
        backgroundColor: '#FF8C42',
        width: 70,
        height: 80,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
        elevation: 6,
    },
    thirdPodium: {
        backgroundColor: '#FF9A56',
        width: 70,
        height: 60,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
        elevation: 6,
    },
    rankNumber: {
        color: '#FFFFFF',
        fontSize: 32,
        fontWeight: '700',
    },
    userName: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '500',
    },
    userCount: {
        color: '#AAAAAA',
        fontSize: 10,
    },
    arrowContainer: {
        alignItems: 'center',
        marginVertical: 15,
    },
    arrow: {
        color: '#AAAAAA',
        fontSize: 20,
    },
    userListContainer: {
        paddingHorizontal: 20,
        marginBottom: 20,
    },
    userListItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: '#1E1E1E',
        borderRadius: 8,
        marginBottom: 8,
    },
    userRankInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    userRank: {
        color: '#FF6B35',
        fontSize: 16,
        fontWeight: 'bold',
        width: 20,
    },
    userListName: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '600',
    },
    userListCount: {
        color: '#AAAAAA',
        fontSize: 14,
    },
    bettingSection: {
        paddingHorizontal: 20,
    },
    bettingSectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    bettingTitle: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '500',
    },
    plusButton: {
        color: '#FF6B35',
        fontSize: 24,
        fontWeight: '300',
    },
    bettingItem: {
        backgroundColor: '#1E1E1E',
        padding: 16,
        borderRadius: 12,
    },
    bettingText: {
        color: '#FFB366',
        fontSize: 14,
        marginBottom: 8,
    },
    timerInfo: {
        alignItems: 'flex-start',
    },
    timerText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: 'bold',
        fontFamily: 'monospace',
    },
    keywordSection: {
        paddingHorizontal: 20,
        paddingBottom: 20,
    },
    keywordHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    keywordTitle: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '500',
    },
    addKeywordButton: {
        backgroundColor: '#FF6B35',
        width: 30,
        height: 30,
        borderRadius: 15,
        justifyContent: 'center',
        alignItems: 'center',
    },
    addKeywordButtonText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: 'bold',
    },
    keywordGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    keywordTag: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: '#FF6B35',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        marginBottom: 8,
        flexShrink: 0,
    },
    keywordText: {
        color: '#FF6B35',
        fontSize: 14,
        flexShrink: 1,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#2E2E2E',
        borderRadius: 12,
        padding: 20,
        width: '80%',
        maxWidth: 300,
    },
    modalTitle: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '500',
        textAlign: 'center',
        marginBottom: 20,
    },
    modalInput: {
        backgroundColor: '#1E1E1E',
        color: '#FFFFFF',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 16,
        marginBottom: 20,
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 10,
    },
    modalButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    cancelButton: {
        backgroundColor: '#555555',
    },
    confirmButton: {
        backgroundColor: '#FF6B35',
    },
    cancelButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '500',
    },
    confirmButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '500',
    },
});

export default styles;
